fix: fix getting `webtorrent` version
Previously, when attempting to use `webtorrent-cli` installed with pnpm, the
following error would occur:

```
❯ webtorrent --help
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/path/to/nodejs/.npm/pnpm-global/5/node_modules/.pnpm/webtorrent-cli@4.0.0/node_modules/webtorrent-cli/node_modules/webtorrent/package.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at file:///path/to/nodejs/.npm/pnpm-global/5/node_modules/.pnpm/webtorrent-cli@4.0.0/node_modules/webtorrent-cli/bin/cmd.js:23:54
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/path/to/nodejs/npm/pnpm-global/5/node_modules/.pnpm/webtorrent-cli@4.0.0/node_modules/webtorrent-cli/node_modules/webtorrent/package.json'
}
```

where `/path/to/nodejs` is the path to my Node.js installation.

This is because the directory structure of the installed
`transmission-cli` is like this:

```
.pnpm/webtorrent-cli@4.0.0
 └ node_modules
   ├ other dependencies...
   ├ webtorrent -> .pnpm/webtorrent@1.5.8/node_modules/webtorrent
   │ ├ index.js
   │ ├ package.json
   │ └ etc...
   └ webtorrent-cli
     ├ bin
     ├ package.json
     └ etc...
```

I got a similar error when installing with npm, which uses a somewhat
similar directory structure:

```
node_modules
 ├ other dependencies...
 ├ webtorrent
 │ ├ index.js
 │ ├ package.json
 │ └ etc...
 └ webtorrent-cli
   ├ bin
   ├ package.json
   └ etc...
```

This commit uses `module.createRequire` to `require` the
`package.json`s. I considered using `require.resolve` to get the correct
`package.json` path instead (and continue to read and parse the file), but to
do that you need to use `createRequire` anyway to get the `require`.