fix: properly import a default export with dynamic 'import'
when using dynamic import function, default exports need to be referenced explicitly.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#importing_defaults

fixes:
```
verifying existing torrent data...

UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/webtorrent/webtorrent-cli/issues

DEBUG INFO: webtorrent-cli 4.0.0, webtorrent 1.5.5, node v17.3.0, linux x64, exit 1
file:///usr/lib/webtorrent-cli/bin/cmd.js:512
      const dlnacasts = (await import('dlnacasts'))()
                                                   ^

TypeError: (intermediate value) is not a function
    at onSelection (file:///usr/lib/webtorrent-cli/bin/cmd.js:512:52)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.3.0
```